apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
spec:
  tls:
    - hosts:
        - richardhere.dev
        - 38.242.149.115
      secretName: richardhere-ssl
  rules:
    - host: richardhere.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80