version: "3.9"
services:

  website:
    build:
      dockerfile: Dockerfile
      context: .
    image: richardhere/website
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://127.0.0.1/" ]
      interval: "1m"
      timeout: "10s"
      retries: 10
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VERSION
      - BUILD
      - ENV
      - LOG_LEVEL
      - SENTRY_DSN