version: "3.9"
services:

  website:
    build:
      dockerfile: Dockerfile
      context: .
    image: richardhere/website
    container_name: richardhere.dev
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "-k", "https://127.0.0.1/" ]
      start_period: 30s
      interval: 1m
      timeout: 5s
      retries: 10
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV
      - VERSION
      - DEPLOY
      - GODOTENV
      - LOG
      - LOG_FILE
      - LOG_LEVEL
      - FIBER_PREFORK
      - SENTRY_DSN
      - SENTRY_TSR